version: "3"
services:
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: awesome
    container_name: "pg_awesome"
  web:
    build: .
    container_name: "awesome"
    environment:
      DATABASE_URL: postgresql://db/awesome
    ports:
      - "4000:4000"
    depends_on:
      - db
