version: "3"
services:
  web:
    build: .
    container_name: "awesome"
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=awesome
    container_name: "pg_awesome"
    ports:
      - "5432:5432"
